import sys
import os
import datetime
from PySide6.QtWidgets import QApplication, QMessageBox, QFileDialog
from PySide6.QtUiTools import QUiLoader
from PySide6.QtCore import QFile, QIODevice

from menu_logic import MenuManager
from translations import TEXTS
from logic import calculate_points, get_verdict # Импортируем нашу логику

def resource_path(relative_path):
    """ Получает абсолютный путь к ресурсам (нужно для PyInstaller) """
    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

def main():
    app = QApplication(sys.argv)

    # 1. ЗАГРУЗКА ИНТЕРФЕЙСА
    ui_file_path = resource_path("ui.ui") 
    ui_file = QFile(ui_file_path)
    
    if not ui_file.open(QIODevice.ReadOnly):
        print(f"Ошибка: Не могу найти файл по пути {ui_file_path}")
        sys.exit(-1)
        
    loader = QUiLoader()
    window = loader.load(ui_file)
    ui_file.close()

    # --- ИНИЦИАЛИЗАЦИЯ МЕНЮ ---
    menu = MenuManager(window)

    # 2. ЛОГИКА СОХРАНЕНИЯ
    def save_decision():
        # Получаем текущий язык интерфейса
        lang = getattr(window, 'current_lang', 'ru') 
        t = TEXTS[lang]

        try:
            # Сбор текста из полей
            text_pp = window.input_pp.toPlainText()
            text_pm = window.input_pm.toPlainText()
            text_mp = window.input_mp.toPlainText()
            text_mm = window.input_mm.toPlainText()
        except AttributeError:
            return

        # Расчет баллов через внешний модуль logic.py
        score_pp = calculate_points(text_pp)
        score_pm = calculate_points(text_pm)
        score_mp = calculate_points(text_mp)
        score_mm = calculate_points(text_mm)

        total_action = score_pp + score_mm
        total_status_quo = score_pm + score_mp

        # Получение вердикта
        verdict_text = get_verdict(total_action, total_status_quo, t)
        final_verdict = f"{verdict_text} ({total_action} vs {total_status_quo})"

        timestamp = datetime.datetime.now().strftime("%d.%m.%Y %H:%M")
        
        # Формирование контента файла
        content = f"""# {t['file_header']} {timestamp}
**ITOG:** {final_verdict}

---

## 1. {t['box_1']}
**{t['score']}: {score_pp}**

{text_pp if text_pp else "—"}

## 2. {t['box_2']}
**{t['score']}: {score_pm}**

{text_pm if text_pm else "—"}

## 3. {t['box_3']}
**{t['score']}: {score_mp}**

{text_mp if text_mp else "—"}

## 4. {t['box_4']}
**{t['score']}: {score_mm}**

{text_mm if text_mm else "—"}

---
*Generated by Descartes Decision Helper*
"""
        # Выбор пути сохранения через системное окно
        default_name = f"decision_{datetime.datetime.now().strftime('%d.%m.%Y_%H-%M')}.txt"
        file_path, _ = QFileDialog.getSaveFileName(
            window, t["menu_open"], default_name, "Text Files (*.txt);;Markdown (*.md)"
        )

        if file_path:
            try:
                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(content)
                
                QMessageBox.information(
                    window, 
                    t["saved_title"], 
                    f"{final_verdict}\n\n{t['saved_body']}:\n{file_path}"
                )
            except Exception as e:
                QMessageBox.critical(window, "Error", f"Could not save file: {str(e)}")

    # Подключение кнопки
    try:
        window.btn_save.clicked.connect(save_decision)
    except AttributeError:
        print("Кнопка btn_save не найдена в ui файле")

    window.show()
    sys.exit(app.exec())

if __name__ == "__main__":
    main()